def send_email(subject: str, sender: str, receiver: str, body: str):
    print("\n" + "=" * 60)
    print("EMAIL CONFIRMATION")
    print("=" * 60)
    print(f"From:    {sender}")
    print(f"To:      {receiver}")
    print(f"Subject: {subject}")
    print("-" * 60)
    print(body)
    print("=" * 60 + "\n")